baseurl = "/"
title = "Ghostwriter example"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
disqusShortname = "XXX"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
Paginate = 5

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Ghostwriter example"
    description = "Ghostwriter example description"
    twitter = "https://twitter.com/XXX"
    github = "https://github.com/XXX" 
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, January 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Latest Post"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Browse Posts"
    url = "/post/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
